In [1]:
from ANN import Network
from ANNNetwork import Network as ANNE

from sklearn import datasets
import pandas as pd
import numpy as np

from typing import List

In [2]:
digits = datasets.load_digits()

In [3]:
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [2]:
def MINST_label_encoder(data: np.ndarray) -> np.ndarray:
    # Encode in a one-hot manner
    def _digit_encoder(datum: int)->List[int]:
        val = np.zeros(10)
        val[datum] = 1
        return val
    return [_digit_encoder(datum).reshape((10, 1)) for datum in data]
            


In [5]:
MINST = [ datum.reshape((64, 1)) for datum in digits.data]

In [67]:
MINST[0].shape

(64, 1)

In [ ]:
MINST_labels = MINST_label_encoder(digits.target)

# Kaggle's MINST

In [3]:
MINST_kaggle = pd.read_csv("./train.csv")
MINST_kaggle_y = MINST_label_encoder(MINST_kaggle["label"].to_numpy())
MINST_kaggle_x = MINST_kaggle.drop("label", axis=1).to_numpy()
MINST_kaggle_x = [ datum.reshape((784, 1)) for datum in MINST_kaggle_x]

# Custom-brewed ANN

In [12]:
ann = Network((784, 100, 10))

In [13]:
ann.feedforward(MINST_kaggle_x[4])[-1]

array([[4.31421209e-01],
       [2.05838134e-02],
       [9.99999990e-01],
       [6.00942592e-01],
       [9.76537675e-01],
       [9.99893481e-01],
       [6.78832633e-04],
       [9.86348940e-01],
       [9.96668875e-01],
       [5.55970133e-03]])

In [6]:
ann.weights

[array([[-0.36421921,  0.80436048, -0.29188819, ...,  0.25377954,
         -0.33766119, -2.28053998],
        [-1.21565004, -0.51079956,  2.15962929, ..., -1.79237858,
          0.05679224, -0.1098274 ],
        [-0.93514079,  0.32144651, -0.39881849, ...,  1.29932403,
         -1.04222999,  2.6737348 ],
        ...,
        [ 1.03553588, -1.17510343,  0.87403172, ..., -0.10377138,
          0.08742564, -0.68475582],
        [ 0.73759938, -0.28058514,  2.14645648, ...,  0.94128029,
          1.04048616, -0.62994099],
        [ 1.42603874,  0.26062758,  1.12633884, ..., -0.96470212,
         -0.60143769, -1.18253124]]),
 array([[-3.77935352e-01, -5.07221333e-02,  1.21989803e+00,
          1.06299184e+00,  3.44865450e-01,  2.36259097e-01,
         -1.34542514e+00, -8.17040270e-01,  4.45955039e-01,
         -2.64093254e-01, -4.14588291e-01, -3.45648857e-01,
          7.24594970e-01, -8.16924076e-01,  2.57624165e+00,
          1.44799383e-01, -6.97386980e-01, -8.79824152e-01,
          1.2

In [14]:
ann.train(MINST_kaggle_x[:1500], MINST_kaggle_y[:1500], epochs=30,eta=10, sgd=False)
"""TODO: Figure out why are the dimensions not mathcing?!"""

'TODO: Figure out why are the dimensions not mathcing?!'

In [15]:
ann.feedforward(MINST_kaggle_x[25])[-1]

array([[6.38164415e-04],
       [1.97401464e-06],
       [6.47320266e-05],
       [7.60255918e-07],
       [1.00505389e-05],
       [2.43904361e-05],
       [9.26111245e-06],
       [3.28418651e-02],
       [9.87423016e-09],
       [6.41364203e-08]])

In [16]:
ann.weights

[array([[-0.18142939,  0.17437262, -0.35671851, ...,  0.39704138,
          1.4194132 ,  0.46113452],
        [-0.12983474,  0.2797298 , -0.60233822, ...,  0.82012166,
         -1.32091233,  0.90717801],
        [-0.32212119, -0.0280148 ,  0.31647181, ...,  0.22073523,
         -0.22242096,  0.76020611],
        ...,
        [ 0.19183598, -0.18470559, -0.86215295, ..., -0.17723621,
         -1.2231421 ,  0.09977271],
        [-0.26875641, -0.98755891,  0.41890566, ...,  0.6455165 ,
          0.09439101,  0.73571198],
        [ 1.30486376, -0.25092259,  2.12847165, ...,  0.34534649,
          0.04433411, -0.67056669]]),
 array([[-1.05378014e+00,  2.38891299e-03,  3.95228162e-02,
         -1.21062802e-01, -5.36171253e-02, -1.20090001e+00,
         -8.78662737e-01,  7.81116715e-01,  1.27812381e+00,
          1.18403489e+00, -1.56799469e+00, -9.82330232e-01,
          7.71730462e-01,  4.75729438e-01,  8.01206506e-02,
         -3.02454393e-01, -1.03988890e+00, -1.21070881e+00,
          8.4

In [17]:
MINST_kaggle_y[25]

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [35]:
MINST_2 = []
for i in range(len(MINST)):
    MINST_2.append([MINST[i], MINST_labels[i]])

In [21]:
ann_2 = ANNE((64, 10, 10))

In [40]:
ann_2.feedforward(MINST[5])

array([[1.70674369e-15],
       [3.10623111e-13],
       [1.59722362e-22],
       [5.02926481e-11],
       [4.92563782e-12],
       [4.73975955e-15],
       [2.48173637e-13],
       [2.74872007e-18],
       [4.90643748e-14],
       [8.44869815e-20]])

In [39]:
ann_2.SGD(MINST_2, 30, 10, 100.)

Epoch 0 complete
Epoch 1 complete
Epoch 2 complete
Epoch 3 complete
Epoch 4 complete
Epoch 5 complete
Epoch 6 complete
Epoch 7 complete
Epoch 8 complete
Epoch 9 complete
Epoch 10 complete
Epoch 11 complete
Epoch 12 complete
Epoch 13 complete
Epoch 14 complete
Epoch 15 complete
Epoch 16 complete
Epoch 17 complete
Epoch 18 complete
Epoch 19 complete
Epoch 20 complete
Epoch 21 complete
Epoch 22 complete
Epoch 23 complete
Epoch 24 complete
Epoch 25 complete
Epoch 26 complete
Epoch 27 complete
Epoch 28 complete
Epoch 29 complete


In [42]:
import pandas as pd

In [46]:
train_MINST = pd.read_csv("./train.csv")

In [52]:
# Form labels from kaggle dataset
MINST_label_2 = MINST_label_encoder(train_MINST["label"].to_numpy())

In [59]:
MINST_data_2 = train_MINST.drop("label", axis=1).to_numpy()

In [70]:
MINST_data_2[0].shape
MINST_train_data = [ datum.reshape((784, 1)) for datum in MINST_data_2]

In [72]:
MINST_train_data[0].shape

(784, 1)

In [75]:
MINST_2_kaggle = []
for i in range(len(MINST_train_data)):
    MINST_2_kaggle.append([MINST_train_data[i], MINST_label_2[i]])

In [63]:
ann_2 = ANNE((784, 100, 10))

In [73]:
ann_2.feedforward(MINST_train_data[10])

/home/joseaguilar/github/ML-Playground/ANN/ANNNetwork.py:137: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0+np.exp(-z))


array([[0.00745102],
       [0.81449791],
       [0.0159455 ],
       [0.98320183],
       [0.99805818],
       [0.75817872],
       [0.8988981 ],
       [0.01918943],
       [0.53354323],
       [0.02744988]])

In [76]:
ann_2.SGD(MINST_2_kaggle[:1500], 30, 10, 100.)

Epoch 0 complete
Epoch 1 complete
Epoch 2 complete
Epoch 3 complete
Epoch 4 complete
Epoch 5 complete
Epoch 6 complete
Epoch 7 complete
Epoch 8 complete
Epoch 9 complete
Epoch 10 complete
Epoch 11 complete
Epoch 12 complete
Epoch 13 complete
Epoch 14 complete
Epoch 15 complete
Epoch 16 complete
Epoch 17 complete
Epoch 18 complete
Epoch 19 complete
Epoch 20 complete
Epoch 21 complete
Epoch 22 complete
Epoch 23 complete
Epoch 24 complete
Epoch 25 complete
Epoch 26 complete
Epoch 27 complete
Epoch 28 complete
Epoch 29 complete


In [77]:
ann_2.feedforward(MINST_train_data[10])

array([[5.11587655e-76],
       [1.00000000e+00],
       [1.10451999e-45],
       [6.25599413e-27],
       [1.47158605e-54],
       [9.67713088e-33],
       [6.02954010e-63],
       [4.93187463e-53],
       [3.12280956e-38],
       [3.86672855e-56]])

# KAGGLE's dataset works on book!