In [1]:
from sklearn import datasets
import numpy
from Perceptron import Perceptron
import random

In [18]:
iris = datasets.load_iris()
indices = [i for i in range(len(iris.data)) if iris.target[i] == 0 or iris.target[i] == 1]
random.shuffle(indices)
X = iris.data[indices]
y = iris.target[indices]

In [19]:
p = Perceptron(input=4)

In [20]:
p.train(X=X[:80], y=y[:80])

label: 0 vs pred: [0]
label: 1 vs pred: [0]
Pred: [0] - actual 1 - false positive
label: 0 vs pred: [1]
Pred: [1] - actual 0 - false negative
label: 0 vs pred: [1]
Pred: [1] - actual 0 - false negative
label: 1 vs pred: [0]
Pred: [0] - actual 1 - false positive
label: 1 vs pred: [1]
label: 0 vs pred: [1]
Pred: [1] - actual 0 - false negative
label: 0 vs pred: [0]
label: 1 vs pred: [0]
Pred: [0] - actual 1 - false positive
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 0 vs pred: [1]
Pred: [1] - actual 0 - false negative
label: 0 vs pred: [0]
label: 0 vs pred: [0]
label: 1 vs pred: [0]
Pred: [0] - actual 1 - false positive
label: 0 vs pred: [1]
Pred: [1] - actual 0 - false negative
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 0 vs pred: [0]
label: 1 vs pred: [1]
label: 0 vs pred: [0]
label: 1 vs pred: [1]
label: 1 vs pred: [1]
label: 0 vs pred: [0]
label: 1 vs pred: [1]
label: 0 vs pred: [0

In [21]:
y

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0])

In [22]:
p.perceptron

array([[-2. , -8. ,  9.5,  3.6]])

In [23]:
[p.feedforward(i) for i in X[80:]]

[array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0])]

In [24]:
y[80:]

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0])

In [9]:
p.perceptron

array([[-2.7, -6.9,  9.6,  4.5]])